import React from 'react'

const FacultiesOrDepartment = [
    "Anatomy",
    "Physiology",
    "Medical Laboratory Science",
    "Nursing Science",
    "Optometry",
    "Public Health",
    "Biochemistry",
    "Computer Science",
    "Industrial Chemistry",
    "Microbiology",
    "Pharmacy",
    "Community medicine",
    "Internal medicine",
    "O&G",
    "Paediatrics",
    "Pharmacology and Therapeutics",
    "Anatomical Pathology",
    "Chemical Pathology",
    "Medical Microbiology",
    "Haematology",
    "Surgery",
    "Consultants",
    "Medical Officers",
    "Doctors",
    "Dieticians",
    "Scientist",
    "Radiologist",
    "Optometrist",
    "Physiotherapy",
    "Mortuary",
    "Nurses",
    "Medical Records",
    "Hospital Pharmacy",
    "Vice Chancellor’s Office",
    "DVC",
    "Registrar’s Office",
    "Bursary’s Office",
    "DAP",
    "Student Affairs",
    "ICT",
    "Post Graduate",
    "JUPEB",
    "Pre-Degree",
    "Library’s Office",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Engineering",
    "Electrical/Electronic Engineering",
    "Food Science and Technology",
    "Mechanical Engineering",
    "Petroleum Engineering",
    "Accounting",
    "Banking and Finance",
    "Business Administration",
    "Entrepreneurship",
    "Marketing",
    "Public Administration",
    "Economics",
    "International Relations",
    "Library and Information Science",
    "Mass Communication",
    "Political Science",
    "Psychology",
    "Sociology",
    "Philosophy",
    "Business Education",
    "Computer Science Education",
    "English Language",
    "Law",
]

const Category = [
    "Professor",
    "Associate Prof",
    "Senior Lecturer",
    "Lecturer 1",
    "Lecturer II",
    "Assistant Lecturer",
    "Graduate Assistant",
    "Non Teaching Staff",
    "Janitor",
    "Senior Staff",
    "Intermediate Staff",
    "Junior Staff",
    "Other"
]

const Position = [
    "Professor",
    "Senior lecturer",
    "Lecturer I",
    "Lecturer II",
    "Assistant lecturer",
    "Graduate Assistant",
    "Consultant",
    "Medical officer",
    "Scientist",
    "Senior Staff",
    "Intermediate staff",
    'Junior staff',
    'Nurse'
]


export { FacultiesOrDepartment, Position, Category }